public enum Fractal {
    MANDELBROT,
    BURNING_SHIP,
    CELTIC,
    BUFFALO,
    TRICORN,
    BURNING_SHIP_MANDLEBAR,
    CELTIC_MANDLEBAR,
    BUFFALO_MANDLEBAR,
    PERPENDICULAR_MANDELBROT,
    PERPENDICULAR_BURNING_SHIP,
    PERPENDICULAR_CELTIC,
    PERPENDICULAR_BUFFALO,
    AIRSHIP,
    TAIL,
    QUILL,
    SHARK_FIN;

    Fractal() {

    }
}
